%Picture of good, bad and ugly functions
clear all, close all
set(0,'defaultaxesfontsize',20,'defaulttextfontsize',20)

xmin=1e4; xmax=1e8;
xlow=1e3; xhigh=1e11; 
kappa=1e2;
ylow=xlow; yhigh=xhigh;

green=[0 0.8 0];
blue=[0.2 0.4 1];
black=[0 0 0];
brown=[0.85 0.55 0.2];
red=[1 0.2 0.2];
white=[1 1 1];
xtick=[1e3 1e7 1e11];

figure; %For the adaptive algorithm
set(gca,'Xscale','log','Yscale','log',...
    'NextPlot','add','Box','on',...
    'xtick',xtick,'ytick',xtick)
patch([xlow xlow xmax xmax xmin xmin xlow],...
    [yhigh xlow xmax xmax*kappa xmin*kappa yhigh yhigh],...
    blue,'EdgeColor',blue)
patch([xlow xhigh xhigh xlow],[xlow xlow xhigh xlow],...
    black,'EdgeColor',black)
patch([xmin xmax xmax xmin xmin],...
    [xmin*kappa xmax*kappa yhigh yhigh xmin*kappa],...
    red,'EdgeColor',red)
patch([xmax xmax xhigh xhigh xmax],...
    [yhigh xmax xhigh yhigh yhigh],...
    brown,'EdgeColor',brown)

axis([xlow xhigh ylow yhigh])
axis square
text('Position',1e4*[1 10],'String','Guaranteed','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',2e8*[1 10],'String','Too Big','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',2e4*[1 10*kappa],'String','Not Guaranteed','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',5e4*[2 1e3*kappa],'String','Nasty','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',[1e7 1e4],'String','Impossible','Rotation',45,...
    'Color',white,'FontWeight','bold')
%text('Position',[1e5 7e1],'Interpreter','Latex',...
%    'String','$$\| f - \mu \|_2^2/\varepsilon^2 \propto$$')
%text('Position',[2e8 7e1],'String','time')
%text('Position',[4e1 1e6],'Interpreter','Latex',...
%     'String','$$\| f - \mu \|_4^2/\varepsilon^2$$','Rotation',90)
text('Position',[1e4 7e1],'Interpreter','Latex',...
    'String','$$\| f - \mu \|_2^2/\varepsilon^2 = \sigma^2/\varepsilon^2 \propto$$')
text('Position',[1.5e9 7e1],'String','time')
text('Position',[4e1 1e4],'Interpreter','Latex',...
    'String','$$\| f - \mu \|_4^2/\varepsilon^2=\sqrt{\kappa}\sigma^2/\varepsilon^2$$','Rotation',90)
text('Position',[2e7 2e11],'String','2 min')
text('Position',[1e3 2e11],'String','0.01 sec')
plot(xmin*[1 1],yhigh*[1 0.6],'k-', ...
    xmax*[1 1],yhigh*[1 0.6],'k-', ...
    'linewidth',2)
posit=get(gca,'Position');
posit(2)=posit(2)+0.05;
posit(3:4)=posit(3:4)*0.95;
set(gca,'Position',posit)
print -depsc AdaptGuaranteedRegion.eps

figure;
set(gca,'Xscale','log','Yscale','log',...
    'NextPlot','add','Box','on',...
    'xtick',xtick,'ytick',xtick)
patch([xlow xlow xmax xmax xlow],...
    [yhigh xlow xmax yhigh yhigh],...
    blue,'EdgeColor',blue)
patch([xlow xhigh xhigh xlow],[xlow xlow xhigh xlow],...
    black,'EdgeColor',black)
patch([xmax xmax xhigh xhigh xmax],...
    [yhigh xmax xhigh yhigh yhigh],...
    brown,'EdgeColor',brown)

axis([xlow xhigh ylow yhigh])
axis square
text('Position',1e4*[1 1e3],'String','Guaranteed','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',2e8*[1 10],'String','Too Big','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',[1e7 1e4],'String','Impossible','Rotation',45,...
    'Color',white,'FontWeight','bold')
text('Position',[1e4 7e1],'Interpreter','Latex',...
    'String','$$\| f - \mu \|_2^2/\varepsilon^2 = \sigma^2/\varepsilon^2 \propto$$')
text('Position',[1.5e9 7e1],'String','time')
text('Position',[4e1 1e4],'Interpreter','Latex',...
    'String','$$\| f - \mu \|_4^2/\varepsilon^2=\sqrt{\kappa}\sigma^2/\varepsilon^2$$','Rotation',90)
text('Position',[2e7 2e11],'String','2 min')
text('Position',[1e3 2e11],'String','0.01 sec')
plot(xmin*[1 1],yhigh*[1 0.6],'k-', ...
    xmax*[1 1],yhigh*[1 0.6],'k-', ...
    'linewidth',2)
posit=get(gca,'Position');
posit(2)=posit(2)+0.05;
posit(3:4)=posit(3:4)*0.95;
set(gca,'Position',posit)
print -depsc NonAdaptGuaranteedRegion.eps

