% Multiple axes example
close all, clear all

n=1000;
x=abs(randn(n,2)).*(ones(n,2)+5*(rand(n,2)>0.8));
prob=((0:n-1)+1/2)/n;
xlowlimit=0.01;
xhilimit=1;
ylowlimit=0.01;
yhilimit=1;
axlinewidth=2;
hs1 = scatter(x(:,1),x(:,2),100,'k','.');
ax1 = gca;
set(ax1,'XColor','k','YColor','k',...
    'XLim',[xlowlimit xhilimit],'YLim',[ylowlimit yhilimit],...
    'XGrid','on','YGrid','on','LineWidth',axlinewidth,'GridLineStyle','--',...
    'XScale','log','Yscale','log')
ax2 = axes('Position',get(ax1,'Position'),...
           'XAxisLocation','bottom',...
           'YAxisLocation','right',...
           'Color','none',...
           'XColor','k','YColor','b',...
           'XLim',[xlowlimit xhilimit],'Xscale','log',...
           'YLim',[0 1],'Linewidth',axlinewidth);
line(sort(x(:,1)),prob,'color','b','linewidth',2)
ax3 = axes('Position',get(ax1,'Position'),...
           'XAxisLocation','top',...
           'YAxisLocation','left',...
           'Color','none',...
           'XColor','r','YColor','k',...
           'Yscale','log',...
           'XLim',[0 1],'YLim',[ylowlimit yhilimit],'Linewidth',axlinewidth);
line(prob,sort(x(:,2)),'color','r','linewidth',2)
print -depsc MultiAxesExample.eps
